# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alexa\Pictures\Proyecto Grado\Interfaces\registroFechas.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Registro_fechas(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 674)
        Form.setStyleSheet("background-color: rgb(3, 169, 244);")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(720, 10, 251, 41))
        self.label_4.setStyleSheet("font: 75 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 381, 41))
        self.label_5.setStyleSheet("font: 75 20pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.comboBoxDia1 = QtWidgets.QComboBox(Form)
        self.comboBoxDia1.setGeometry(QtCore.QRect(400, 70, 69, 22))
        self.comboBoxDia1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxDia1.setObjectName("comboBoxDia1")
        self.comboBoxMes1 = QtWidgets.QComboBox(Form)
        self.comboBoxMes1.setGeometry(QtCore.QRect(540, 70, 69, 22))
        self.comboBoxMes1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxMes1.setObjectName("comboBoxMes1")
        self.comboBoxDia2 = QtWidgets.QComboBox(Form)
        self.comboBoxDia2.setGeometry(QtCore.QRect(760, 70, 69, 22))
        self.comboBoxDia2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxDia2.setObjectName("comboBoxDia2")
        self.comboBoxMes2 = QtWidgets.QComboBox(Form)
        self.comboBoxMes2.setGeometry(QtCore.QRect(900, 70, 69, 22))
        self.comboBoxMes2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxMes2.setObjectName("comboBoxMes2")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(200, 70, 151, 31))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe Print\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(340, 70, 47, 20))
        self.label_14.setStyleSheet("font: 8pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(490, 70, 47, 21))
        self.label_15.setStyleSheet("font: 8pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(650, 70, 31, 21))
        self.label_16.setStyleSheet("font: 8pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(700, 70, 41, 20))
        self.label_17.setStyleSheet("font: 8pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(850, 70, 47, 21))
        self.label_18.setStyleSheet("font: 8pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 110, 1251, 541))
        self.frame.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(110, 20, 901, 491))
        self.groupBox_3.setStyleSheet("border: 1px solid gray;\n"
"font: 75 12pt \"Century Gothic\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tablePrimerasFechas = QtWidgets.QTableWidget(self.groupBox_3)
        self.tablePrimerasFechas.setGeometry(QtCore.QRect(20, 40, 861, 131))
        self.tablePrimerasFechas.setStyleSheet("font: 75 8pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tablePrimerasFechas.setObjectName("tablePrimerasFechas")
        self.tablePrimerasFechas.setColumnCount(6)
        self.tablePrimerasFechas.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePrimerasFechas.setItem(5, 5, item)
        self.tablePrimerasFechas.horizontalHeader().setDefaultSectionSize(137)
        self.tableFechasAlternas = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableFechasAlternas.setGeometry(QtCore.QRect(20, 190, 861, 131))
        self.tableFechasAlternas.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Century Gothic\";")
        self.tableFechasAlternas.setObjectName("tableFechasAlternas")
        self.tableFechasAlternas.setColumnCount(6)
        self.tableFechasAlternas.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechasAlternas.setItem(5, 5, item)
        self.tableFechasAlternas.horizontalHeader().setDefaultSectionSize(136)
        self.tablePereiraDomingos = QtWidgets.QTableWidget(self.groupBox_3)
        self.tablePereiraDomingos.setGeometry(QtCore.QRect(20, 340, 861, 131))
        self.tablePereiraDomingos.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Century Gothic\";")
        self.tablePereiraDomingos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tablePereiraDomingos.setObjectName("tablePereiraDomingos")
        self.tablePereiraDomingos.setColumnCount(6)
        self.tablePereiraDomingos.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePereiraDomingos.setItem(5, 5, item)
        self.tablePereiraDomingos.horizontalHeader().setDefaultSectionSize(137)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(140, 10, 121, 16))
        self.label.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"border-color: #fff;")
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(410, 10, 121, 16))
        self.label_12.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"border-color: #fff;")
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(680, 10, 121, 16))
        self.label_19.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"border-color: #fff;")
        self.label_19.setObjectName("label_19")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_6.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.label_7.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 290, 91, 21))
        self.label_9.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 270, 81, 21))
        self.label_8.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 400, 81, 21))
        self.label_20.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(10, 420, 91, 21))
        self.label_21.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(1030, 120, 191, 301))
        self.groupBox_2.setStyleSheet("border: 1px solid gray;\n"
"font: 75 10pt \"Century Gothic\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnRegistrarFechas = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRegistrarFechas.setGeometry(QtCore.QRect(10, 70, 171, 51))
        self.btnRegistrarFechas.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(117, 117, 117);\n"
"font:75 11pt \"Century Gothic\";\n"
"")
        self.btnRegistrarFechas.setObjectName("btnRegistrarFechas")
        self.btnEliminarFechas = QtWidgets.QPushButton(self.groupBox_2)
        self.btnEliminarFechas.setGeometry(QtCore.QRect(10, 210, 171, 51))
        self.btnEliminarFechas.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(117, 117, 117);\n"
"font:75 11pt \"Century Gothic\";\n"
"")
        self.btnEliminarFechas.setObjectName("btnEliminarFechas")
        self.btnActualizarFechas = QtWidgets.QPushButton(self.groupBox_2)
        self.btnActualizarFechas.setGeometry(QtCore.QRect(10, 140, 171, 51))
        self.btnActualizarFechas.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(117, 117, 117);\n"
"font:75 11pt \"Century Gothic\";")
        self.btnActualizarFechas.setObjectName("btnActualizarFechas")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Registro de fechas</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Programación encuentros tutoriales -</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p>INTRODUCTORIO:</p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Dia:</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Mes:</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Y</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Dia:</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Mes:</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Form", "Fechas"))
        item = self.tablePrimerasFechas.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tablePrimerasFechas.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tablePrimerasFechas.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tablePrimerasFechas.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tablePrimerasFechas.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tablePrimerasFechas.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePrimerasFechas.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tablePrimerasFechas.isSortingEnabled()
        self.tablePrimerasFechas.setSortingEnabled(False)
        item = self.tablePrimerasFechas.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePrimerasFechas.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tablePrimerasFechas.setSortingEnabled(__sortingEnabled)
        item = self.tableFechasAlternas.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableFechasAlternas.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableFechasAlternas.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableFechasAlternas.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableFechasAlternas.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableFechasAlternas.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableFechasAlternas.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableFechasAlternas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableFechasAlternas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableFechasAlternas.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableFechasAlternas.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableFechasAlternas.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tableFechasAlternas.isSortingEnabled()
        self.tableFechasAlternas.setSortingEnabled(False)
        item = self.tableFechasAlternas.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableFechasAlternas.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tableFechasAlternas.setSortingEnabled(__sortingEnabled)
        item = self.tablePereiraDomingos.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tablePereiraDomingos.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tablePereiraDomingos.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tablePereiraDomingos.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tablePereiraDomingos.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tablePereiraDomingos.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablePereiraDomingos.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tablePereiraDomingos.isSortingEnabled()
        self.tablePereiraDomingos.setSortingEnabled(False)
        item = self.tablePereiraDomingos.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablePereiraDomingos.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tablePereiraDomingos.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "BLOQUE A"))
        self.label_12.setText(_translate("Form", "BLOQUE B"))
        self.label_19.setText(_translate("Form", "BLOQUE C"))
        self.label_6.setText(_translate("Form", "PRIMERAS"))
        self.label_7.setText(_translate("Form", "FECHAS"))
        self.label_9.setText(_translate("Form", "ALTERNAS"))
        self.label_8.setText(_translate("Form", "FECHAS"))
        self.label_20.setText(_translate("Form", "PEREIRA"))
        self.label_21.setText(_translate("Form", "DOMINGOS"))
        self.groupBox_2.setTitle(_translate("Form", "OPCIONES"))
        self.btnRegistrarFechas.setText(_translate("Form", "REGISTRAR FECHAS"))
        self.btnEliminarFechas.setText(_translate("Form", "ELIMINAR FECHAS"))
        self.btnActualizarFechas.setText(_translate("Form", "ACTUALIZAR FECHAS"))
