# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alexa\Pictures\Proyecto Grado\Interfaces\ventanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from GUI.ActualizarAsignaturas import ActualizarAsignatura
from GUI.ActualizarDocentes import ActualizarDocente
from GUI.eliminarAsignatura import EliminarAsignatura
from GUI.eliminarDocente import EliminarDocente
from GUI.registroAsignaturas import RegistroAsignaturas
from GUI.registroDocentes import RegistroDocentes


class VentanaPrincipal(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1362, 854)
        MainWindow.setStyleSheet("\n"
"\n"
"background-color: rgb(3, 169, 244);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -20, 1821, 871))
        self.frame.setStyleSheet("\n"
"background-color: rgb(3, 169, 244);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(520, 10, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 75 8pt \"Century Gothic\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1362, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuAsignaturas = QtWidgets.QMenu(self.menubar)
        self.menuAsignaturas.setObjectName("menuAsignaturas")
        self.menuDocentes = QtWidgets.QMenu(self.menubar)
        self.menuDocentes.setObjectName("menuDocentes")
        self.menuFechas = QtWidgets.QMenu(self.menubar)
        self.menuFechas.setObjectName("menuFechas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegistrar_espacios_fisicos = QtWidgets.QAction(MainWindow)
        self.actionRegistrar_espacios_fisicos.setWhatsThis("")
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_espacios_fisicos.setFont(font)
        self.actionRegistrar_espacios_fisicos.setAutoRepeat(False)
        self.actionRegistrar_espacios_fisicos.setIconVisibleInMenu(False)
        self.actionRegistrar_espacios_fisicos.setObjectName("actionRegistrar_espacios_fisicos")
        self.actionRegistrar_docentes = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_docentes.setFont(font)
        self.actionRegistrar_docentes.setObjectName("actionRegistrar_docentes")
        self.actionRegistro_intensidad_horaria = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistro_intensidad_horaria.setFont(font)
        self.actionRegistro_intensidad_horaria.setObjectName("actionRegistro_intensidad_horaria")
        self.actionGenerar_reportes = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionGenerar_reportes.setFont(font)
        self.actionGenerar_reportes.setObjectName("actionGenerar_reportes")
        self.actionRegistrar_Asignaturas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_Asignaturas.setFont(font)
        self.actionRegistrar_Asignaturas.setObjectName("actionRegistrar_Asignaturas")
        self.actionRegistrar_Asignaturas_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionRegistrar_Asignaturas_2.setFont(font)
        self.actionRegistrar_Asignaturas_2.setObjectName("actionRegistrar_Asignaturas_2")
        self.actionModificar_Asignaturas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionModificar_Asignaturas.setFont(font)
        self.actionModificar_Asignaturas.setObjectName("actionModificar_Asignaturas")
        self.actionEliminar_Asignaturas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionEliminar_Asignaturas.setFont(font)
        self.actionEliminar_Asignaturas.setObjectName("actionEliminar_Asignaturas")
        self.actionVer_fechas_alternas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionVer_fechas_alternas.setFont(font)
        self.actionVer_fechas_alternas.setObjectName("actionVer_fechas_alternas")
        self.actionRegistrar_Docente = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionRegistrar_Docente.setFont(font)
        self.actionRegistrar_Docente.setObjectName("actionRegistrar_Docente")
        self.actionActualizar_docente = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionActualizar_docente.setFont(font)
        self.actionActualizar_docente.setObjectName("actionActualizar_docente")
        self.actionEliminar_docente = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionEliminar_docente.setFont(font)
        self.actionEliminar_docente.setObjectName("actionEliminar_docente")
        self.actionRegistrar_fechas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionRegistrar_fechas.setFont(font)
        self.actionRegistrar_fechas.setObjectName("actionRegistrar_fechas")
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionGenerar_reportes)
        self.menuOpciones.addAction(self.actionVer_fechas_alternas)
        self.menuAsignaturas.addAction(self.actionRegistrar_Asignaturas_2)
        self.menuAsignaturas.addAction(self.actionModificar_Asignaturas)
        self.menuAsignaturas.addAction(self.actionEliminar_Asignaturas)
        self.menuDocentes.addAction(self.actionRegistrar_Docente)
        self.menuDocentes.addAction(self.actionActualizar_docente)
        self.menuDocentes.addAction(self.actionEliminar_docente)
        self.menuFechas.addSeparator()
        self.menuFechas.addAction(self.actionRegistrar_fechas)
        self.menubar.addAction(self.menuAsignaturas.menuAction())
        self.menubar.addAction(self.menuDocentes.menuAction())
        self.menubar.addAction(self.menuFechas.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        self.actionRegistrar_Docente.triggered.connect(self.ventana_registro_docente)
        self.actionActualizar_docente.triggered.connect(self.ventana_actualizar_docente)
        self.actionEliminar_docente.triggered.connect(self.ventana_eliminar_docente)
        self.actionRegistrar_Asignaturas_2.triggered.connect(self.ventana_registro_asignatura)
        self.actionModificar_Asignaturas.triggered.connect(self.ventana_actualizar_asignatura)
        self.actionEliminar_Asignaturas.triggered.connect(self.ventana_eliminar_asignatura)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def ventana_registro_docente(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = RegistroDocentes()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def ventana_actualizar_docente(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = ActualizarDocente()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def ventana_eliminar_docente(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = EliminarDocente()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def ventana_registro_asignatura(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = RegistroAsignaturas()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def ventana_actualizar_asignatura(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = ActualizarAsignatura()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def ventana_eliminar_asignatura(self):
            self.ventana = QtWidgets.QMainWindow()
            self.ui = EliminarAsignatura()
            self.ui.setup_ui(self.ventana)
            self.ventana.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">¡Bienvenido a SS MEWIN!</span></p><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Programador de horarios</span></p></body></html>"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Reportes"))
        self.menuAsignaturas.setTitle(_translate("MainWindow", "Asignaturas"))
        self.menuDocentes.setTitle(_translate("MainWindow", "Docentes"))
        self.menuFechas.setTitle(_translate("MainWindow", "Fechas"))
        self.actionRegistrar_espacios_fisicos.setText(_translate("MainWindow", "Registrar espacios fisicos"))
        self.actionRegistrar_docentes.setText(_translate("MainWindow", "Registrar docentes"))
        self.actionRegistro_intensidad_horaria.setText(_translate("MainWindow", "Registrar intensidad horaria"))
        self.actionGenerar_reportes.setText(_translate("MainWindow", "Ver primeras fechas"))
        self.actionRegistrar_Asignaturas.setText(_translate("MainWindow", "Registrar Asignaturas"))
        self.actionRegistrar_Asignaturas_2.setText(_translate("MainWindow", "Registrar asignaturas"))
        self.actionModificar_Asignaturas.setText(_translate("MainWindow", "Modificar asignaturas"))
        self.actionEliminar_Asignaturas.setText(_translate("MainWindow", "Eliminar asignaturas"))
        self.actionVer_fechas_alternas.setText(_translate("MainWindow", "Ver fechas alternas"))
        self.actionRegistrar_Docente.setText(_translate("MainWindow", "Registrar docente"))
        self.actionActualizar_docente.setText(_translate("MainWindow", "Actualizar docente"))
        self.actionEliminar_docente.setText(_translate("MainWindow", "Eliminar docente"))
        self.actionRegistrar_fechas.setText(_translate("MainWindow", "Registrar fechas"))
