# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alexa\Pictures\Proyecto Grado\Interfaces\ventanaPrincipal.ui'
#
# Created by: PyQt5 GUI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class VentanaPrincipal(QtWidgets.QMainWindow):

    def setup_ui(self, form):
        form.setObjectName("form")
        form.resize(1246, 854)
        form.setStyleSheet("\n"
"\n"
"background-color: rgb(3, 169, 244);")
        self.centralwidget = QtWidgets.QWidget(form)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -20, 1821, 871))
        self.frame.setStyleSheet("\n"
"background-color: rgb(3, 169, 244);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(520, 10, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 75 8pt \"Century Gothic\";")
        self.label.setObjectName("label")
        form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1246, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuAsignaturas = QtWidgets.QMenu(self.menubar)
        self.menuAsignaturas.setObjectName("menuAsignaturas")
        self.menuDocentes = QtWidgets.QMenu(self.menubar)
        self.menuDocentes.setObjectName("menuDocentes")
        self.menuFechas = QtWidgets.QMenu(self.menubar)
        self.menuFechas.setObjectName("menuFechas")
        form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(form)
        self.statusbar.setObjectName("statusbar")
        form.setStatusBar(self.statusbar)
        self.actionRegistrar_espacios_fisicos = QtWidgets.QAction(form)
        self.actionRegistrar_espacios_fisicos.setWhatsThis("")
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_espacios_fisicos.setFont(font)
        self.actionRegistrar_espacios_fisicos.setAutoRepeat(False)
        self.actionRegistrar_espacios_fisicos.setIconVisibleInMenu(False)
        self.actionRegistrar_espacios_fisicos.setObjectName("actionRegistrar_espacios_fisicos")
        self.actionRegistrar_docentes = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_docentes.setFont(font)
        self.actionRegistrar_docentes.setObjectName("actionRegistrar_docentes")
        self.actionRegistro_intensidad_horaria = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistro_intensidad_horaria.setFont(font)
        self.actionRegistro_intensidad_horaria.setObjectName("actionRegistro_intensidad_horaria")
        self.actionGenerar_reportes = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionGenerar_reportes.setFont(font)
        self.actionGenerar_reportes.setObjectName("actionGenerar_reportes")
        self.actionRegistrar_Asignaturas = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionRegistrar_Asignaturas.setFont(font)
        self.actionRegistrar_Asignaturas.setObjectName("actionRegistrar_Asignaturas")
        self.actionRegistrar_Asignaturas_2 = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionRegistrar_Asignaturas_2.setFont(font)
        self.actionRegistrar_Asignaturas_2.setObjectName("actionRegistrar_Asignaturas_2")
        self.actionModificar_Asignaturas = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionModificar_Asignaturas.setFont(font)
        self.actionModificar_Asignaturas.setObjectName("actionModificar_Asignaturas")
        self.actionEliminar_Asignaturas = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionEliminar_Asignaturas.setFont(font)
        self.actionEliminar_Asignaturas.setObjectName("actionEliminar_Asignaturas")
        self.actionVer_fechas_alternas = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.actionVer_fechas_alternas.setFont(font)
        self.actionVer_fechas_alternas.setObjectName("actionVer_fechas_alternas")
        self.actionActualizar_Docente = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionActualizar_Docente.setFont(font)
        self.actionActualizar_Docente.setObjectName("actionActualizar_Docente")
        self.actionEliminar_docente = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionEliminar_docente.setFont(font)
        self.actionEliminar_docente.setObjectName("actionEliminar_docente")
        self.actionEliminar_docente_2 = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionEliminar_docente_2.setFont(font)
        self.actionEliminar_docente_2.setObjectName("actionEliminar_docente_2")
        self.actionRegistrar_fechas = QtWidgets.QAction(form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.actionRegistrar_fechas.setFont(font)
        self.actionRegistrar_fechas.setObjectName("actionRegistrar_fechas")
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionGenerar_reportes)
        self.menuOpciones.addAction(self.actionVer_fechas_alternas)
        self.menuAsignaturas.addAction(self.actionRegistrar_Asignaturas_2)
        self.menuAsignaturas.addAction(self.actionModificar_Asignaturas)
        self.menuAsignaturas.addAction(self.actionEliminar_Asignaturas)
        self.menuDocentes.addAction(self.actionActualizar_Docente)
        self.menuDocentes.addAction(self.actionEliminar_docente)
        self.menuDocentes.addAction(self.actionEliminar_docente_2)
        self.menuFechas.addSeparator()
        self.menuFechas.addAction(self.actionRegistrar_fechas)
        self.menubar.addAction(self.menuAsignaturas.menuAction())
        self.menubar.addAction(self.menuDocentes.menuAction())
        self.menubar.addAction(self.menuFechas.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">¡Bienvenido a SS MEWIN!</span></p><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Programador de horarios</span></p></body></html>"))
        self.menuOpciones.setTitle(_translate("Form", "Reportes"))
        self.menuAsignaturas.setTitle(_translate("Form", "Asignaturas"))
        self.menuDocentes.setTitle(_translate("Form", "Docentes"))
        self.menuFechas.setTitle(_translate("Form", "Fechas"))
        self.actionRegistrar_espacios_fisicos.setText(_translate("Form", "Registrar espacios fisicos"))
        self.actionRegistrar_docentes.setText(_translate("Form", "Registrar docentes"))
        self.actionRegistro_intensidad_horaria.setText(_translate("Form", "Registrar intensidad horaria"))
        self.actionGenerar_reportes.setText(_translate("Form", "Ver primeras fechas"))
        self.actionRegistrar_Asignaturas.setText(_translate("Form", "Registrar Asignaturas"))
        self.actionRegistrar_Asignaturas_2.setText(_translate("Form", "Registrar asignaturas"))
        self.actionModificar_Asignaturas.setText(_translate("Form", "Modificar asignaturas"))
        self.actionEliminar_Asignaturas.setText(_translate("Form", "Eliminar asignaturas"))
        self.actionVer_fechas_alternas.setText(_translate("Form", "Ver fechas alternas"))
        self.actionActualizar_Docente.setText(_translate("Form", "Registrar docente"))
        self.actionEliminar_docente.setText(_translate("Form", "Actualizar docente"))
        self.actionEliminar_docente_2.setText(_translate("Form", "Eliminar docente"))
        self.actionRegistrar_fechas.setText(_translate("Form", "Registrar fechas"))
